import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as Yup from "yup";
// check if email is valid.
let regex = RegExp("[a-z0-9]+@[a-z]+.[a-z]{2,3}");

export default function Home() {
  // form validation rules
  const validationSchema = Yup.object().shape({
    firstName: Yup.string().required("First name cannot be empty."),
    lastName: Yup.string().required("Last name cannot be empty."),
    email: Yup.string()
      .required("Email cannot be empty.")
      .email("Looks like this is not an email."),
    password: Yup.string()
      .min(3, "Password must be at least 3 characters")
      .required("Password is required"),
  });

  const formOptions = { resolver: yupResolver(validationSchema) };
  // get functions to build form with useForm() hook
  const { register, handleSubmit, reset, formState } = useForm(formOptions);
  const { errors } = formState;

  function onSubmit(data) {
    // display form data on success
    alert("SUCCESS!! :-)\n\n" + JSON.stringify(data, null, 4));
    return false;
  }

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={`${styles.section} ${styles.top}`}>
        <h2 className={styles.h2}>Learn to code by watching others</h2>
        <p className={styles.p}>
          See how experienced developers solve problems in real-time. Watching
          scripited tutorials is great, but understanding how developers think
          is invaluable.
        </p>
      </div>
      <div className={styles.section}>
        <div className={styles.article}>
          <p className={styles.p}>
            <span className={styles.span}>Try it free 7 days</span> then $20/mo
            thereafter
          </p>
        </div>
        <form className={styles.form} action="">
          <ul className={styles.ul}>
            <li className={styles.li} id="first_name">
              <input
                type="text"
                name="firstName"
                className={styles.input}
                placeholder="First Name"
              />
              <Image
                className={`${styles.noshow} ${styles.errorIcon}`}
                src="/warning.png"
                alt="error warning"
                width={"1rem"}
                height={"1rem"}
              />
              <small className={styles.noshow}>First name cannot be empty.</small>
            </li>
            <li className={styles.li} id="last_name">
              <input
                className={styles.input}
                type="text"
                placeholder="Last Name"
              />
              <Image
                className={`${styles.noshow} ${styles.errorIcon}`}
                src="/warning.png"
                alt="error warning"
                width={"1rem"}
                height={"1rem"}
              />
              <small className={styles.noshow}>Last name cannot be empty.</small>
            </li>
            <li className={styles.li} id="email">
              <input
                className={styles.input}
                type="text"
                placeholder="Email Address"
              />
              <Image
                className={`${styles.noshow} ${styles.errorIcon}`}
                src="/warning.png"
                alt="error warning"
                width={"1rem"}
                height={"1rem"}
              />
              <small className={styles.noshow}>Email cannot be empty.</small>
              <small className={styles.noshow}>Looks like this is not an email.</small>
            </li>
            <li className={styles.li} id="password">
              <input
                className={styles.input}
                type="password"
                placeholder="Password"
              />
              <Image
                className={`${styles.noshow} ${styles.errorIcon}`}
                src="/warning.png"
                alt="error warning"
                width={"1rem"}
                height={"1rem"}
              />
              <small className={styles.noshow}>Password cannot be empty.</small>
            </li>
            <li className={styles.li}>
              <button className={styles.button}>CLAIM YOUR FREE TRIAL</button>
            </li>
          </ul>
          <p className={styles.p}>
            By clicking on the button you are agreeing to
            <br />
            our
            <span className={styles.span}>Terms and Services</span>
          </p>
        </form>
      </div>
    </div>
  );
}
