import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={`${styles.section} ${styles.top}`}>
        <h2 classNmae={styles.h2}>Learn to code by watching others</h2>
        <p classNmae={styles.p}>
          See how experienced developers solve problems in real-time. Watching
          scripited tutorials is great, but understanding how developers think
          is invaluable.
        </p>
      </div>
      <div className={styles.section}>
        <div className={styles.article}>
          <p classNmae={styles.p}>
            <span classNmae={styles.span}>Try it free 7 days</span> then $20/mo
            thereafter
          </p>
        </div>
        <form className={styles.form} action="">
          <ul className={styles.ul}>
            <li className={styles.li} id="first_name">
              <input
                className={styles.input}
                type="text"
                placeholder="First Name"
              />
            </li>
            <li className={styles.li} id="last_name">
              <input
                className={styles.input}
                type="text"
                placeholder="Last Name"
              />
            </li>
            <li className={styles.li} id="email">
              <input
                className={styles.input}
                type="text"
                placeholder="Email Address"
              />
            </li>
            <li className={styles.li} id="password">
              <input
                className={styles.input}
                type="password"
                placeholder="Password"
              />
            </li>
            <li className={styles.li}>
              <button className={styles.button}>CLAIM YOUR FREE TRIAL</button>
            </li>
          </ul>
          <p classNmae={styles.p}>
            By clicking on the button you are agreeing to
            <br />
            our
            <span classNmae={styles.span}>Terms and Services</span>
          </p>
        </form>
      </div>
    </div>
  );
}
