import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRef, useState, useEffect } from "react";
// check if email is valid.
let regex = RegExp("[a-z0-9]+@[a-z]+.[a-z]{2,3}");

export default function Home() {
  // form validation rules
  const formRef = useRef(null);
  const [formSubmit, SetFormSubmit] = useRef(false);

  const myFunc = (e) => {
    e.preventDefault();

    if (formRef) {
      let firstName = formRef.current.querySelector("#first_name");
      let lastName = formRef.current.querySelector("#last_name");
      let email = formRef.current.querySelector("#email");
      let password = formRef.current.querySelector("#password");

      firstName.children[0].value === ""
        ? ((firstName.children[0].placeholder = ""),
          firstName.children[1].classList.remove(styles.noshow))
        : firstName.children[1].classList.add(styles.noshow);

      lastName.children[0].value === ""
        ? ((lastName.children[0].placeholder = ""),
          lastName.children[1].classList.remove(styles.noshow))
        : lastName.children[1].classList.add(styles.noshow);

      email.children[0].value === "" || !regex.test(email.children[0].value)
        ? ((email.children[0].placeholder = ""),
          email.children[1].classList.remove(styles.noshow))
        : email.children[1].classList.add(styles.noshow);

      password.children[0].value === ""
        ? ((password.children[0].placeholder = ""),
          password.children[1].classList.remove(styles.noshow))
        : password.children[1].classList.add(styles.noshow);
    }
  };

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={`${styles.section} ${styles.top}`}>
        <h2 className={styles.h2}>Learn to code by watching others</h2>
        <p className={styles.p}>
          See how experienced developers solve problems in real-time. Watching
          scripited tutorials is great, but understanding how developers think
          is invaluable.
        </p>
      </div>
      <div className={styles.section}>
        <div className={styles.article}>
          <p className={styles.p}>
            <span className={styles.span}>Try it free 7 days</span> then $20/mo
            thereafter
          </p>
        </div>
        <form onSubmit={myFunc} ref={formRef} className={styles.form} action="">
          <ul className={styles.ul}>
            <li className={styles.li} id="first_name">
              <input
                type="text"
                name="firstName"
                className={styles.input}
                placeholder="First Name"
              />
              <div className={styles.noshow}>
                <div className={`${styles.errorIcon}`}>
                  <Image
                    src="/warning.png"
                    alt="error warning"
                    width={"20%"}
                    height={"20%"}
                  />
                </div>
                <small className={styles.small}>
                  First name cannot be empty.
                </small>
              </div>
            </li>
            <li className={styles.li} id="last_name">
              <input
                className={styles.input}
                type="text"
                placeholder="Last Name"
              />
              <div className={styles.noshow}>
                <div className={`${styles.errorIcon}`}>
                  <Image
                    src="/warning.png"
                    alt="error warning"
                    width={"20%"}
                    height={"20%"}
                  />
                </div>
                <small className={styles.small}>
                  Last name cannot be empty.
                </small>
              </div>
            </li>
            <li className={styles.li} id="email">
              <input
                className={styles.input}
                type="text"
                placeholder="Email Address"
              />
              <div className={styles.noshow}>
                <div className={`${styles.errorIcon}`}>
                  <Image
                    src="/warning.png"
                    alt="error warning"
                    width={"20%"}
                    height={"20%"}
                  />
                </div>
                <small className={styles.small}>
                  Email cannot be empty or looks like this is not an email.
                </small>
              </div>
            </li>
            <li className={styles.li} id="password">
              <input
                className={styles.input}
                type="password"
                placeholder="Password"
              />
              <div className={styles.noshow}>
                <div className={`${styles.errorIcon}`}>
                  <Image
                    src="/warning.png"
                    alt="error warning"
                    width={"20%"}
                    height={"20%"}
                  />
                </div>
                <small className={styles.small}>
                  Password cannot be empty.
                </small>
              </div>
            </li>
            <li className={styles.li}>
              <button className={styles.button}>CLAIM YOUR FREE TRIAL</button>
            </li>
          </ul>
          <p className={styles.p}>
            By clicking on the button you are agreeing to
            <br />
            our
            <span className={styles.span}>Terms and Services</span>
          </p>
        </form>
      </div>
    </div>
  );
}
